version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/ACS/acs_cte_forward_model/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
  - package-ecosystem: "pip"
    directory: "notebooks/ACS/acs_findsat_mrt/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
