version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
    labels:
      - "github-actions dependencies"
  - package-ecosystem: "pip"
    directory: "notebooks/ACS/acs_cte_forward_model/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
    labels:
      - "pip dependencies"
  - package-ecosystem: "pip"
    directory: "notebooks/ACS/acs_findsat_mrt/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
    labels:
      - "pip dependecies"
  - package-ecosystem: "pip"
    directory: "notebooks/ACS/acs_pixel_area_maps/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
    labels:
      - "pip dependencies"
  - package-ecosystem: "pip"
    directory: "notebooks/ACS/acs_polarization_tools/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
    labels:
      - "pip dependencies"
  - package-ecosystem: "pip"
    directory: "notebooks/ACS/acs_reduction/"
    schedule:
     interval: "weekly"
     day: "sunday"
     time: "12:00"
    labels:
      - "pip dependencies"
