name: Manual Execute All Notebooks
on:
  workflow_dispatch:

jobs:
  ExecuteNotebooks:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_scheduled.yml@multi_dev
   with:
      python-version: ${{ vars.PYTHON_VERSION }}
