name: Jupyter Notebook Accessibility Check

on:
  workflow_dispatch:
    paths:
      - 'notebooks/*/*/*.ipynb'

jobs:
    notebook-accessibility-check:
      uses: spacetelescope/notebook-ci-actions/.github/workflows/notebook_accessibility_check.yml@new_a11y_nb_checker