name: Update Dependabot Config File
# 1: Create branch
# 2: execute script on branch
# 2a: if dependabot.yml not updated, discard branch
# 3: if dependabot.yml updated, create PR to merge new branch into main
# 4: Auto-approve PR (If possible)
on:
  workflow_dispatch:

jobs:
  update-dependabot-config-file:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.8.12
        uses: actions/setup-python@v4 ## needed for caching
        with:
          python-version: 3.8.12
          cache: 'pip'
      - name: Add conda to system path
        run: |
          # $CONDA is an environment variable pointing to the root of the miniconda directory
          echo $CONDA/bin >> $GITHUB_PATH
      - name: Run dependabot config file updater script
        run: |
          python .github/scripts/make_dependabot_file.py
