name: Weekly broken link check
on:
  schedule:
    - cron: '0 4 * * 0' # 0400 UTC every Sunday
  workflow_dispatch:

jobs:
  Scheduled:
   uses: spacetelescope/notebook-ci-actions/.github/workflows/broken_link_checker.yml@v3
